### ISSUE TITLE
[번역중] getting started

### ISSUE THREAD

**Issue by ejolie** [Yeonjj/javascript-tutorial-ko#22]
안녕하세요. 
최근에 자바스크립트에 대한 좋은 자료를 찾아서 혼자 공부할 겸 번역을 해보려다 
이미 진행중인 분들이 계셔서 함께하고자 합니다.

파일 위치 : 
1-js/01-getting-started/1-intro/article.md
1-js/01-getting-started/2-code-editor/article.md
1-js/01-getting-started/3-devtools/article.md
완료 기간 : 18.12.20

**Comment by Yeonjj** [comment]
환영합니다! 관리의 편의를 위해서 collaborator초대 보내드렸습니다.

**Comment by ejolie** [comment]
번역 완료했습니다.

**Comment by Yeonjj** [comment]
넵 혹시 pr 리뷰대로 merge해도 될까요?

**Comment by ejolie** [comment]
네~ 감사합니다!
