### ISSUE TITLE
[번역중] 1-js/04-object-basics/01, 02, 03

### ISSUE THREAD

**Issue by ejolie** [Yeonjj/javascript-tutorial-ko#28]
파일 위치 :
1-js/04-object-basics/01-object/article.md
1-js/04-object-basics/02-garbage-collection/article.md
1-js/04-object-basics/03-symbol/article.md
완료 기간 : 19.01.20

**Comment by Violet-Bora-Lee** [comment]
@ejolie 님 안녕하세요. 한국어 리드 [리파지터리](https://github.com/Violet-Bora-Lee/javascript-tutorial-ko)를 운영하고 있는 @Violet-Bora-Lee 입니다. 

다름이 아니라, 완료하신 3가지 md파일의 번역물을 머지하려고 하는데 01-object/article.md 파일은 중간까지 번역된 걸 풀 받아 왔는데, 다른 두 파일의 번역물은 찾을 수 없어서요. 아직 푸시 못하신건지 아니면 제가 못 찾는 것인지 궁금해서 코멘트 남깁니다.

**Comment by ejolie** [comment]
안녕하세요! 
완성된 번역본의 주소는 javascript tutorial - Task Manager 에 작성한 뒤, 
@Violet-Bora-Lee 님 repo로 PR 보냈습니다. 
혹시 잘못된 게 있다면 다시 알려주시면 감사하겠습니다~🙇
