### ISSUE TITLE
오타 제보합니다.

### ISSUE THREAD

**Issue by soyoungsoo** [Yeonjj/javascript-tutorial-ko#6]
번역 감사드립니다 :)

내용 : `만약 우리가 animal에 어떤 메소드를 가지고 있다면, rabbit에서도 호촐할 수 있습니다.`
* `호촐` - > `호출`

위치 : 
https://github.com/Yeonjj/javascript-tutorial-ko/blob/master/1-js/07-object-oriented-programming/03-prototype-inheritance/article.md

**Comment by Yeonjj** [comment]
제보 감사드립니다. 오타 수정하였습니다 ^^
